### ISSUE TITLE
Update block url from Special:Blockip to Special:Block

### ISSUE THREAD

**Issue by Pix1234** [countervandalism/CVNBot#36]
For example: <SWBot3> New user [[simple:User:Shinewin2xw1xofxggrmrvbbg7sisbp]] created. Block: https://simple.wikipedia.org/wiki/Special:Blockip/Shinewin2xw1xofxggrmrvbbg7sisbp

**Comment by Krinkle** [comment]
@Pix1234 Can you explain what the problem is?

**Comment by Pix1234** [comment]
Shouldnt it be just special:block?

**Comment by Krinkle** [comment]
@Pix1234 It works both ways. The block system used to be called "Blockip" (because it was created for blocking IP addresses, the ability to block user names was created afterwards, about 10 years ago). It has been renamed to "Block", but the old name still works.

The CVNBot software is old and therefore uses the old name. The link is not broken though, and it works both ways.

**Comment by MarcoAurelioWM** [comment]
PR #38 should fix this.

**Comment by Krinkle** [comment]
@MarcoAurelioWM Thanks! I'll deploy this now.
